'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Heart,Search,Check,Layers,SlidersHorizontal,MessageCircle,Plus,Minus,Expand,ArrowUpRight,Grid2X2,Bookmark,X,Package,ChevronLeft,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import type {Product,Category,Config,Variant} from '@/lib/catalog-types';
import {api,money,thumb} from '@/lib/catalog-client';
const defaults:Config={name:'The Rug Edit',whatsapp:'',design:'gallery',currency:'INR'};
function Choose({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:[string,string][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="choose" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>;}
function Picture({src,name,large=false}:{src:string;name:string;large?:boolean}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return failed||!src?<div className="no-picture"><Package size={36}/><span>Image unavailable</span></div>:<img src={large?src:thumb(src)} alt={name} width="480" height="480" loading={large?'eager':'lazy'} decoding="async" onError={()=>setFailed(true)}/>;}
export default function Catalog(){
 const [config,setConfig]=useState(defaults),[cats,setCats]=useState<Category[]>([]),[products,setProducts]=useState<Product[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [q,setQ]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[sort,setSort]=useState('name'),[stock,setStock]=useState(false),[savedOnly,setSavedOnly]=useState(false),[saved,setSaved]=useState<string[]>([]),[storageReady,setStorageReady]=useState(false),[selected,setSelected]=useState<Record<string,Product>>({}),[enquiry,setEnquiry]=useState(false);
 const [detail,setDetail]=useState<Product|null>(null),[detailLoading,setDetailLoading]=useState(false),[related,setRelated]=useState<Product[]>([]),[imageIndex,setImageIndex]=useState(0),[lightbox,setLightbox]=useState(false),[variant,setVariant]=useState<Variant|null>(null);
 const cache=useRef(new Map<string,any>()),detailCache=useRef(new Map<string,any>()),detailVersion=useRef(0);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('catalog-wishlist')||'[]');if(Array.isArray(s))setSaved(s.filter(x=>typeof x==='string'));}catch{}setStorageReady(true);Promise.all([api('/api/catalog?mode=config'),api('/api/catalog?mode=categories')]).then(([c,ct])=>{setConfig(c);setCats(ct)}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(storageReady)try{localStorage.setItem('catalog-wishlist',JSON.stringify(saved));}catch{toast.error('This browser could not save the wishlist.');}},[saved,storageReady]);
 useEffect(()=>{const t=setTimeout(()=>{setQuery(q);setPage(1)},220);return()=>clearTimeout(t);},[q]);
 const key=new URLSearchParams({q:query,category,sort,stock:stock?'1':'0',page:String(page),limit:'24',...(savedOnly?{ids:saved.length?saved.join(','):'__empty__'}:{})}).toString();
 useEffect(()=>{let alive=true;const abort=new AbortController();setError('');const current=cache.current.get(key);if(current){setProducts(current.products);setTotal(current.total);setLoading(false);}else setLoading(true);
 api('/api/catalog?'+key,{signal:abort.signal}).then(d=>{cache.current.set(key,d);if(alive){setProducts(d.products);setTotal(d.total);setLoading(false);}}).catch(e=>{if(alive&&e.name!=='AbortError'){setError(e.message);setLoading(false);}});return()=>{alive=false;abort.abort();};},[key]);
 const toggleSaved=useCallback((id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]),[]);
 function toggleSelected(p:Product){setSelected(s=>{const next={...s};if(next[p.id])delete next[p.id];else {if(Object.keys(next).length>=100){toast.error('Select up to 100 products per enquiry.');return s;}next[p.id]=p;}return next;});}
 async function openProduct(p:Product){const version=++detailVersion.current;setDetail(p);setRelated([]);setVariant(null);setImageIndex(0);setDetailLoading(true);let d=detailCache.current.get(p.id);try{if(!d){d=await api('/api/catalog?mode=detail&id='+encodeURIComponent(p.id));detailCache.current.set(p.id,d);}if(version!==detailVersion.current)return;setDetail(d.product);setRelated(d.related);setVariant(d.product.variants?.[0]||null);}catch(e:any){toast.error(e.message);}finally{if(version===detailVersion.current)setDetailLoading(false);}}
 function prefetch(p:Product){if(detailCache.current.has(p.id))return;api('/api/catalog?mode=detail&id='+encodeURIComponent(p.id)).then(d=>detailCache.current.set(p.id,d)).catch(()=>{});}
 function productUrl(p:Product){return location.origin+'/?product='+encodeURIComponent(p.id);}
 function message(list:Product[]){return 'Hi, I am interested in the following products:\n'+list.map((p,i)=>`${i+1}. ${p.name}${p.variants?.[0]?.name?' ('+p.variants[0].name+')':''} | SKU: ${p.sku}\n${productUrl(p)}`).join('\n')+'\nPlease share more details and pricing.';}
 function whatsApp(list:Product[]){if(!config.whatsapp){toast.error('WhatsApp contact has not been configured yet.');return;}window.open('https://wa.me/'+config.whatsapp+'?text='+encodeURIComponent(message(list)),'_blank','noopener,noreferrer');}
 useEffect(()=>{const id=new URLSearchParams(location.search).get('product');if(id)openProduct({id,name:'Product',images:[],price:0,currency:'INR',source:'',sku:'',externalId:'',categoryId:'',available:false});},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const abort=new AbortController();Promise.resolve(context.registerTool({name:'search_catalog',description:'Search the catalog and display matching products.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input:any){if(!input||typeof input.query!=='string'||input.query.length>100)throw new Error('A query up to 100 characters is required.');const d=await api('/api/catalog?q='+encodeURIComponent(input.query));setQ(input.query);setQuery(input.query);setCategory('');setSavedOnly(false);setStock(false);setSort('name');setPage(1);setProducts(d.products);setTotal(d.total);return {total:d.total,products:d.products.map((p:Product)=>({id:p.id,name:p.name,price:p.price}))};}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort();},[]);
 const list=Object.values(selected),active=category?cats.find(c=>c.id===category)?.name:'All rugs';
 function changeCat(id:string){setCategory(id);setPage(1);setSavedOnly(false);}
 function card(p:Product){return <article className="product" key={p.id}><div className="product-visual"><button className="product-open" onClick={()=>openProduct(p)} onMouseEnter={()=>prefetch(p)} onFocus={()=>prefetch(p)} aria-label={'View '+p.name}><Picture src={p.images[0]} name={p.name}/></button><button className={'save-button '+(saved.includes(p.id)?'is-saved':'')} onClick={()=>toggleSaved(p.id)} aria-label={(saved.includes(p.id)?'Remove from':'Add to')+' wishlist: '+p.name}><Heart size={18} fill={saved.includes(p.id)?'currentColor':'none'}/></button><span className={'stock-tag '+(!p.available?'out':'')}>{p.available?'Available':'Out of stock'}</span><button className={'select-product '+(selected[p.id]?'picked':'')} onClick={()=>toggleSelected(p)} aria-label={(selected[p.id]?'Deselect ':'Select ')+p.name}>{selected[p.id]?<Check size={16}/>:<Plus size={16}/>}<span>{selected[p.id]?'Selected':'Enquire'}</span></button></div><div className="product-caption"><div><span className="category-label">{p.categoryName}</span><button className="product-name" onClick={()=>openProduct(p)}>{p.name}</button><span className="sku">{p.sku}</span></div><strong>{money(p)}</strong></div></article>;}
 return <div className={'catalog design-'+config.design}><Toaster position="bottom-center" richColors/><div className="top-strip"><span>Explore. Save. Enquire.</span><span className="sample-notice">Sample collection · AI-generated photographs</span></div><header className="catalog-header"><a className="brand" href="/"><span className="brand-mark"><Layers size={22}/></span><span>{config.name}<small>THE COLLECTION</small></span></a><div className="header-actions"><button className={savedOnly?'active':''} onClick={()=>{setSavedOnly(!savedOnly);setPage(1)}}><Heart size={20}/><span>Wishlist</span><b>{saved.length}</b></button><button onClick={()=>setEnquiry(true)}><Bookmark size={20}/><span>Selected</span><b>{list.length}</b></button><a href="/admin" className="admin-link">Manage catalog</a></div></header>
 <main><div className="collection-intro"><div><span className="eyebrow">TEXTURE. COLOUR. CHARACTER.</span><h1>{savedOnly?'Your favourites':'Find your next favourite.'}</h1><p>{savedOnly?'A collection worth coming back to.':'Explore the collection, keep what you love, and ask us about the details.'}</p></div><div className="collection-count"><b>{savedOnly?saved.length:cats.reduce((a,c)=>a+c.count,0)}</b><span>{savedOnly?'saved pieces':'pieces to explore'}</span></div></div>
 <nav className="category-nav" aria-label="Collections"><button className={!category&&!savedOnly?'current':''} onClick={()=>changeCat('')}><Grid2X2 size={16}/>All rugs</button>{cats.map(c=><button className={category===c.id?'current':''} key={c.id} onClick={()=>changeCat(c.id)}>{c.parentId?'↳ ':''}{c.name}<span>{c.count}</span></button>)}</nav>
 <section className="catalog-toolbar"><label className="search-field"><Search size={19}/><input value={q} maxLength={100} onChange={e=>setQ(e.target.value)} placeholder="Search designs, colours or SKU…" aria-label="Search products"/>{q&&<button onClick={()=>setQ('')} aria-label="Clear search"><X size={16}/></button>}</label><div className="filter-controls"><label className="check-label"><Checkbox checked={stock} onCheckedChange={v=>{setStock(v===true);setPage(1)}}/>In stock only</label><Choose value={sort} onChange={v=>{setSort(v);setPage(1)}} label="Sort products" items={[["name","Name: A–Z"],["price-low","Price: low to high"],["price-high","Price: high to low"]]}/></div></section>
 <div className="results-line"><h2>{savedOnly?'Wishlist':active}</h2><span>{loading?'Loading collection…':`${total} ${total===1?'piece':'pieces'}`}</span></div>
 {error?<div className="empty-state"><Package/><h3>We couldn’t load the collection.</h3><p>{error}</p><button className="primary" onClick={()=>location.reload()}>Try again</button></div>:loading?<div className="product-grid">{Array.from({length:8},(_,i)=><div key={i} className="product"><Skeleton className="aspect-square rounded-none"/><Skeleton className="h-5 w-3/4 mt-4"/><Skeleton className="h-4 w-1/3 mt-2"/></div>)}</div>:products.length?<div className="product-grid">{products.map(card)}</div>:<div className="empty-state"><Heart size={32}/><h3>{savedOnly?'Keep your favourites here.':'No matching pieces.'}</h3><p>{savedOnly?'Tap the heart on any rug to save it on this device.':'Try another search or collection.'}</p><button className="primary" onClick={()=>{setQ('');setQuery('');setCategory('');setSavedOnly(false);setStock(false);setPage(1)}}>Browse all rugs</button></div>}
 {total>24&&<nav className="page-nav" aria-label="Product pages"><button disabled={page===1} onClick={()=>{setPage(p=>p-1);window.scrollTo({top:250,behavior:'smooth'})}}><ChevronLeft size={17}/>Previous</button><span>Page {page} of {Math.ceil(total/24)}</span><button disabled={page>=Math.ceil(total/24)} onClick={()=>{setPage(p=>p+1);window.scrollTo({top:250,behavior:'smooth'})}}>Next<ChevronRight size={17}/></button></nav>}
 </main><footer className="catalog-footer"><span className="brand-small">{config.name}</span><span>Found something you love? Let’s talk.</span><button onClick={()=>{if(list.length){setEnquiry(true)}else if(config.whatsapp){window.open('https://wa.me/'+config.whatsapp,'_blank','noopener,noreferrer')}else toast.error('Configure WhatsApp in the admin workspace first.')}}><MessageCircle size={18}/>Contact on WhatsApp</button></footer>
 {list.length>0&&<div className="selection-bar"><div><span className="selection-number">{list.length}</span><span>{list.length===1?'piece':'pieces'} selected</span><button onClick={()=>setSelected({})}>Clear</button></div><button className="primary" onClick={()=>setEnquiry(true)}><MessageCircle size={18}/>Review enquiry</button></div>}
 <Dialog open={!!detail} onOpenChange={v=>{if(!v){detailVersion.current++;setDetail(null)}}}><DialogContent className="detail-dialog"><DialogTitle className="sr-only">{detail?.name||'Product details'}</DialogTitle><DialogDescription className="sr-only">Product images, specifications, availability, and enquiry options.</DialogDescription>{detail&&<><div className="detail-layout"><div><button className="detail-image" onClick={()=>setLightbox(true)} aria-label="Open image lightbox"><Picture src={detail.images[imageIndex]} name={detail.name} large/><span><Expand size={18}/> View image</span></button>{detail.images.length>1&&<div className="thumbnails">{detail.images.map((s,i)=><button key={s+i} className={i===imageIndex?'active':''} onClick={()=>setImageIndex(i)} aria-label={'Image '+(i+1)}><Picture src={s} name={detail.name}/></button>)}</div>}</div><div className="detail-text"><span className="eyebrow">{detail.categoryName}</span><h2>{detail.name}</h2><p className="sku">SKU: {variant?.sku||detail.sku}</p><strong className="detail-price">{money({...detail,price:variant?.price??detail.price})}</strong><span className={'availability '+(!(variant?.available??detail.available)?'out':'')}>{(variant?.available??detail.available)?'Available for enquiry':'Currently out of stock'}</span>{detailLoading?<Skeleton className="h-24 w-full my-6"/>:<><p className="description">{detail.description||'Contact us for product details.'}</p>{!!detail.variants?.length&&<label className="field-label">Size / variant<Choose value={variant?.id||detail.variants[0].id} onChange={id=>setVariant(detail.variants?.find(v=>v.id===id)||null)} label="Product variant" items={detail.variants.map(v=>[v.id,v.name+(v.available?'':' · out of stock')])}/></label>}<div className="detail-buttons"><button className="primary" onClick={()=>whatsApp([{...detail,price:variant?.price??detail.price,sku:variant?.sku||detail.sku,variants:variant?[variant]:[]}])}><MessageCircle size={18}/>Enquire on WhatsApp</button><button className="secondary" onClick={()=>toggleSelected({...detail,price:variant?.price??detail.price,sku:variant?.sku||detail.sku,variants:variant?[variant]:[]})}>{selected[detail.id]?<Check size={18}/>:<Plus size={18}/>} {selected[detail.id]?'Added to enquiry':'Add to enquiry'}</button><button className="quiet" onClick={()=>toggleSaved(detail.id)}><Heart size={18} fill={saved.includes(detail.id)?'currentColor':'none'}/>{saved.includes(detail.id)?'Saved to wishlist':'Save to wishlist'}</button></div></>}</div></div>{related.length>0&&<div className="related"><h3>You might also like</h3><div>{related.map(p=><button key={p.id} onClick={()=>openProduct(p)}><Picture src={p.images[0]} name={p.name}/><span>{p.name}</span><strong>{money(p)}</strong></button>)}</div></div>}</>}</DialogContent></Dialog>
 <Dialog open={lightbox} onOpenChange={setLightbox}><DialogContent className="lightbox-dialog"><DialogTitle className="sr-only">{detail?.name} image {imageIndex+1}</DialogTitle><DialogDescription className="sr-only">Full image. Use navigation to view other product images.</DialogDescription>{detail&&<><Picture src={detail.images[imageIndex]} name={detail.name} large/><div className="lightbox-nav"><button disabled={imageIndex===0} onClick={()=>setImageIndex(i=>i-1)} aria-label="Previous image"><ChevronLeft/></button><span>{imageIndex+1} / {detail.images.length||1}</span><button disabled={imageIndex>=detail.images.length-1} onClick={()=>setImageIndex(i=>i+1)} aria-label="Next image"><ChevronRight/></button></div></>}</DialogContent></Dialog>
 <Sheet open={enquiry} onOpenChange={setEnquiry}><SheetContent className="enquiry-sheet"><SheetTitle>Your enquiry</SheetTitle><SheetDescription>Select your pieces and send us one message.</SheetDescription><div className="enquiry-items">{list.length?list.map(p=><div key={p.id}><Picture src={p.images[0]} name={p.name}/><span><b>{p.name}</b><small>{p.sku}</small><strong>{money(p)}</strong></span><button onClick={()=>toggleSelected(p)} aria-label={'Remove '+p.name}><X size={18}/></button></div>):<p>No products selected yet. Use “Enquire” on any product.</p>}</div>{list.length>0&&<><label className="field-label">Message preview<textarea value={message(list)} readOnly rows={7}/></label><button className="primary" onClick={()=>whatsApp(list)}><MessageCircle size={19}/>Send on WhatsApp</button><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(message(list));toast.success('Enquiry copied.')}catch{toast.error('Please select and copy the message above.')}}}>Copy message</button></>}{!config.whatsapp&&<p className="notice">The catalog owner has not set a WhatsApp number yet. You can copy your enquiry in the meantime.</p>}</SheetContent></Sheet>
 </div>;}
