import { sqliteTable, text, integer, real, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
export const categories = sqliteTable('categories', { id:text('id').primaryKey(),name:text('name').notNull(),parentId:text('parent_id'),visible:integer('visible').notNull().default(1),sortOrder:integer('sort_order').notNull().default(0) });
export const products = sqliteTable('products', { id:text('id').primaryKey(),externalId:text('external_id').notNull(),source:text('source').notNull(),name:text('name').notNull(),sku:text('sku').notNull(),price:real('price').notNull(),currency:text('currency').notNull().default('INR'),description:text('description').notNull(),categoryId:text('category_id').notNull(),available:integer('available').notNull(),images:text('images').notNull(),variants:text('variants').notNull(),url:text('url').notNull(),metadata:text('metadata').notNull(),fingerprint:text('fingerprint').notNull(),suppressed:integer('suppressed').notNull().default(0),updatedAt:text('updated_at').notNull() }, t=>[uniqueIndex('products_source_external').on(t.source,t.externalId),index('products_category_visible').on(t.categoryId,t.suppressed),index('products_source').on(t.source)]);
export const settings=sqliteTable('settings',{id:text('id').primaryKey(),value:text('value').notNull()});
export const fixtures=sqliteTable('fixtures',{id:text('id').primaryKey(),source:text('source').notNull(),payload:text('payload').notNull()});
export const syncRuns=sqliteTable('sync_runs',{id:text('id').primaryKey(),source:text('source').notNull(),status:text('status').notNull(),startedAt:text('started_at').notNull(),finishedAt:text('finished_at'),added:integer('added').notNull().default(0),updated:integer('updated').notNull().default(0),unchanged:integer('unchanged').notNull().default(0),error:text('error')});
export const syncLocks=sqliteTable('sync_locks',{source:text('source').primaryKey(),expiresAt:integer('expires_at').notNull()});

export const loginLimits=sqliteTable('login_limits',{id:text('id').primaryKey(),attempts:integer('attempts').notNull(),windowStart:integer('window_start').notNull()});
