import {env} from 'cloudflare:workers';
export const SESSION_COOKIE='catalog-admin-session';
export const SESSION_SECONDS=8*60*60;
const enc=new TextEncoder();
function hex(bytes:ArrayBuffer){return Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,'0')).join('');}
function b64(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
function unb64(s:string){if(!/^[A-Za-z0-9_-]+$/.test(s))throw Error('Invalid token');const t=s.replaceAll('-','+').replaceAll('_','/');return Uint8Array.from(atob(t+'='.repeat((4-t.length%4)%4)),x=>x.charCodeAt(0));}
async function signingKey(){const secret=String((env as any).CATALOG_SECRET||'');if(!/^[a-f0-9]{64}$/.test(secret))throw Error('Session signing is not configured.');const material=await crypto.subtle.digest('SHA-256',enc.encode('catalog-admin-session-v1:'+secret));return crypto.subtle.importKey('raw',material,{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
async function passwordVersion(){return hex(await crypto.subtle.digest('SHA-256',enc.encode(String((env as any).ADMIN_DEMO_PASSWORD_HASH||''))));}
export async function checkDemoCredentials(email:string,password:string){const configured=String((env as any).ADMIN_DEMO_EMAIL||'').toLowerCase();const stored=String((env as any).ADMIN_DEMO_PASSWORD_HASH||'');const [format,rounds,salt,expected]=stored.split(':');if(!configured||format!=='pbkdf2-sha256'||rounds!=='100000'||!/^[a-f0-9]{32}$/.test(salt||'')||!/^[a-f0-9]{64}$/.test(expected||''))return false;const key=await crypto.subtle.importKey('raw',enc.encode(password),{name:'PBKDF2'},false,['deriveBits']);const bytes=await crypto.subtle.deriveBits({name:'PBKDF2',salt:Uint8Array.from(salt.match(/../g)!,x=>parseInt(x,16)),iterations:100000,hash:'SHA-256'},key,256);const actual=hex(bytes);let diff=0;for(let i=0;i<expected.length;i++)diff|=actual.charCodeAt(i)^expected.charCodeAt(i);return diff===0&&email.trim().toLowerCase()===configured;}
export async function createSession(){const payload=b64(enc.encode(JSON.stringify({email:String((env as any).ADMIN_DEMO_EMAIL).toLowerCase(),expires:Date.now()+SESSION_SECONDS*1000,version:await passwordVersion(),nonce:crypto.randomUUID()})));const signature=b64(new Uint8Array(await crypto.subtle.sign('HMAC',await signingKey(),enc.encode(payload))));return payload+'.'+signature;}
export async function validSession(token:string|undefined){try{if(!token||token.length>1500)return false;const parts=token.split('.');if(parts.length!==2)return false;const [payload,signature]=parts;if(!await crypto.subtle.verify('HMAC',await signingKey(),unb64(signature),enc.encode(payload)))return false;const p=JSON.parse(new TextDecoder().decode(unb64(payload)));return typeof p.expires==='number'&&p.expires>Date.now()&&p.expires<=Date.now()+SESSION_SECONDS*1000&&p.email===String((env as any).ADMIN_DEMO_EMAIL||'').toLowerCase()&&p.version===await passwordVersion();}catch{return false;}}
export function sessionCookie(value:string,seconds=SESSION_SECONDS){return `${SESSION_COOKIE}=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${seconds}`;}
