import {env} from 'cloudflare:workers';
import {db,slug,getConfig} from './catalog-data';
import type {Normalized,Variant} from './catalog-types';
export type Connection={type:'shopify'|'woocommerce';domain:string;token?:string;key?:string;secret?:string;currency?:string};
export class SourceError extends Error{}
async function cryptoKey(){const hex=String((env as any).CATALOG_SECRET||'');if(!/^[a-f0-9]{64}$/.test(hex))throw new SourceError('Secure connection storage is not configured.');return crypto.subtle.importKey('raw',Uint8Array.from(hex.match(/../g)!,x=>parseInt(x,16)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function saveConnection(c:Connection){validateDomain(c);const iv=crypto.getRandomValues(new Uint8Array(12));const data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await cryptoKey(),new TextEncoder().encode(JSON.stringify(c))));const value=JSON.stringify({iv:Array.from(iv),data:Array.from(data)});await db().prepare('INSERT INTO settings(id,value) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind('connection-'+c.type,value).run();}
export async function readConnection(type:string):Promise<Connection|null>{const row=await db().prepare('SELECT value FROM settings WHERE id=?').bind('connection-'+type).first<any>();if(row){const d=JSON.parse(row.value);const text=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(d.iv)},await cryptoKey(),new Uint8Array(d.data));return JSON.parse(new TextDecoder().decode(text));}
 const e=env as any;if(type==='shopify'&&e.SHOPIFY_DOMAIN&&e.SHOPIFY_ACCESS_TOKEN)return {type:'shopify',domain:e.SHOPIFY_DOMAIN,token:e.SHOPIFY_ACCESS_TOKEN};if(type==='woocommerce'&&e.WOOCOMMERCE_URL&&e.WOOCOMMERCE_KEY&&e.WOOCOMMERCE_SECRET)return {type:'woocommerce',domain:e.WOOCOMMERCE_URL,key:e.WOOCOMMERCE_KEY,secret:e.WOOCOMMERCE_SECRET,currency:(await getConfig()).currency};return null;}
export function validateDomain(c:Connection){if(c.type==='shopify'){if(!/^[a-z0-9][a-z0-9-]*\.myshopify\.com$/i.test(c.domain))throw new SourceError('Use your store-name.myshopify.com domain, without https://.');if(!c.token)throw new SourceError('A Shopify Admin API access token is required.');return;}
 let u:URL;try{u=new URL(c.domain);}catch{throw new SourceError('Enter a valid HTTPS WooCommerce store URL.');}if(u.protocol!=='https:'||u.username||u.password||u.port||u.search||u.hash||!u.hostname.includes('.')||/^(?:\d+\.){3}\d+$/.test(u.hostname)||u.hostname.includes(':')||/(^|\.)(localhost|local|internal|test|invalid|example)$/.test(u.hostname))throw new SourceError('Use a public HTTPS store domain. IP addresses and internal hosts are not supported.');if(!c.key||!c.secret)throw new SourceError('A WooCommerce consumer key and secret are required.');}
async function fetchJSON(url:string,init:RequestInit={}){for(let attempt=0;attempt<3;attempt++){let res:Response;try{res=await fetch(url,{...init,redirect:'error',signal:AbortSignal.timeout(25000)});}catch{throw new SourceError('The store did not respond. Check its address and try again.');}if((res.status===429||res.status>=500)&&attempt<2){const delay=Math.min(3000,Number(res.headers.get('retry-after')||1)*1000);await new Promise(r=>setTimeout(r,delay));continue;}if(!res.ok)throw new SourceError(res.status===401||res.status===403?'The store rejected access. Check the credentials and API permissions.':'The store returned HTTP '+res.status+'. The existing catalog was preserved.');let data:any;try{data=await res.json();}catch{throw new SourceError('The store returned an invalid API response.');}return {data,res};}throw new SourceError('The store is busy. Try again shortly.');}
const variantFields='id title sku price inventoryQuantity inventoryPolicy inventoryItem { tracked } selectedOptions { name value }';
export function normalizeShopify(p:any,currency:string):Normalized {const categoryName=p.productType||p.collections?.nodes?.[0]?.title||p.category?.name||'Uncategorized';const vars:Variant[]=(p.variants?.nodes||[]).map((v:any)=>({id:v.id,name:v.title,sku:v.sku||'',price:Number(v.price),available:v.inventoryPolicy==='CONTINUE'||v.inventoryItem?.tracked===false||Number(v.inventoryQuantity)>0,attributes:Object.fromEntries((v.selectedOptions||[]).map((o:any)=>[o.name,o.value]))}));return {externalId:p.id,source:'shopify',name:p.title,sku:vars[0]?.sku||p.handle,price:Math.min(...vars.map(v=>v.price)),currency,description:p.description||'',categoryName,categoryId:slug(categoryName),available:p.status==='ACTIVE'&&vars.some(v=>v.available),images:(p.images?.nodes||[]).map((x:any)=>x.url).filter(safeImage),variants:vars,url:p.onlineStoreUrl||'',metadata:{vendor:p.vendor,tags:p.tags,collections:p.collections?.nodes||[],status:p.status,sourceUpdatedAt:p.updatedAt,seo:p.seo}};}
export function normalizeWoo(p:any,currency:string,variations:any[]=[]):Normalized {const categoryName=p.categories?.[0]?.name||'Uncategorized';const variants=variations.map(v=>({id:String(v.id),name:(v.attributes||[]).map((a:any)=>a.option).join(' / ')||'Variation',sku:v.sku||'',price:Number(v.price||0),available:v.stock_status!=='outofstock',attributes:Object.fromEntries((v.attributes||[]).map((a:any)=>[a.name,a.option]))}));return {externalId:String(p.id),source:'woocommerce',name:p.name,sku:p.sku||String(p.id),price:Number(p.price||0),currency,description:String(p.description||p.short_description||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').trim(),categoryName,categoryId:slug(categoryName),available:p.status==='publish'&&p.stock_status!=='outofstock',images:(p.images||[]).map((i:any)=>i.src).filter(safeImage),variants,url:p.permalink||'',metadata:{categories:p.categories,attributes:p.attributes,tags:p.tags,dimensions:p.dimensions,weight:p.weight,sourceUpdatedAt:p.date_modified_gmt,status:p.status}};}
function safeImage(s:string){try{return new URL(s).protocol==='https:';}catch{return false;}}
export async function importShopify(c:Connection){validateDomain(c);const endpoint='https://'+c.domain+'/admin/api/'+((env as any).SHOPIFY_API_VERSION||'2026-07')+'/graphql.json';const query=`query Catalog($after:String){shop{currencyCode}products(first:10,after:$after){nodes{id title handle description vendor productType status tags onlineStoreUrl updatedAt seo{title description}category{name}collections(first:10){nodes{id title}}images(first:100){nodes{url}pageInfo{hasNextPage endCursor}}variants(first:100){nodes{${variantFields}}pageInfo{hasNextPage endCursor}}}pageInfo{hasNextPage endCursor}}}`;
 async function gql(query:string,variables:any){for(let retry=0;retry<3;retry++){const {data}=await fetchJSON(endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-Shopify-Access-Token':c.token!},body:JSON.stringify({query,variables})});if(data.errors){if(data.errors.every((e:any)=>e.extensions?.code==='THROTTLED')&&retry<2){await new Promise(r=>setTimeout(r,1500));continue;}throw new SourceError('Shopify could not read the catalog. Confirm read_products and read_inventory scopes.');}if(!data.data)throw new SourceError('Shopify returned an incomplete response.');return data.data;}throw new SourceError('Shopify is rate limiting requests. Try again.');}
 const items:Normalized[]=[];let after=null;
 for(let page=0;page<50;page++){const data=await gql(query,{after});for(const p of data.products.nodes){let vpage=p.variants.pageInfo;for(let vp=0;vpage.hasNextPage;vp++){if(vp>=20)throw new SourceError('A product exceeds the supported variant limit. Existing data was preserved.');const d=await gql(`query More($id:ID!,$after:String){product(id:$id){variants(first:100,after:$after){nodes{${variantFields}}pageInfo{hasNextPage endCursor}}}}`,{id:p.id,after:vpage.endCursor});p.variants.nodes.push(...d.product.variants.nodes);vpage=d.product.variants.pageInfo;}
 let ipage=p.images.pageInfo;for(let ip=0;ipage.hasNextPage;ip++){if(ip>=10)throw new SourceError('A product exceeds the supported image limit.');const d=await gql('query More($id:ID!,$after:String){product(id:$id){images(first:100,after:$after){nodes{url}pageInfo{hasNextPage endCursor}}}}',{id:p.id,after:ipage.endCursor});p.images.nodes.push(...d.product.images.nodes);ipage=d.product.images.pageInfo;}
 items.push(normalizeShopify(p,data.shop.currencyCode));}
 if(!data.products.pageInfo.hasNextPage)return items;after=data.products.pageInfo.endCursor;}
 throw new SourceError('This version supports up to 500 products per store. No partial import was saved.');}
export async function importWoo(c:Connection){validateDomain(c);const base=c.domain.replace(/\/$/,'')+'/wp-json/wc/v3';const headers={Authorization:'Basic '+btoa(c.key+':'+c.secret)};let currency=c.currency||(await getConfig()).currency;
 // Currency is explicitly selected during connection setup, never inferred from price strings.
 const items:Normalized[]=[];for(let page=1;page<=5;page++){const {data,res}=await fetchJSON(base+'/products?per_page=100&page='+page,{headers});if(!Array.isArray(data))throw new SourceError('WooCommerce returned an invalid product list.');for(const p of data){const vars:any[]=[];if(p.type==='variable'){for(let vp=1;vp<=20;vp++){const v=await fetchJSON(base+'/products/'+p.id+'/variations?per_page=100&page='+vp,{headers});if(!Array.isArray(v.data))throw new SourceError('WooCommerce returned invalid variations.');vars.push(...v.data);if(v.data.length<100)break;if(vp===20)throw new SourceError('A product exceeds the supported variant limit.');}}items.push(normalizeWoo(p,currency,vars));}
 const pages=Number(res.headers.get('x-wp-totalpages')||0);if((pages&&page>=pages)||data.length<100)return items;}
 throw new SourceError('This version supports up to 500 products per store. No partial import was saved.');}
