import {readFile,mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import assert from 'node:assert/strict';import ts from 'typescript';
const out=await mkdtemp(path.join(tmpdir(),'catalog-check-'));
const sqlite=new DatabaseSync(':memory:');sqlite.exec(await readFile('drizzle/0000_damp_fenris.sql','utf8'));
class Statement{constructor(sql,args=[]){this.sql=sql;this.args=args}bind(...args){return new Statement(this.sql,args)}async first(){return sqlite.prepare(this.sql).get(...this.args)||null}async all(){return {results:sqlite.prepare(this.sql).all(...this.args)}}async run(){const r=sqlite.prepare(this.sql).run(...this.args);return {meta:{changes:Number(r.changes)}}}}
const db={prepare:sql=>new Statement(sql),async batch(stmts){sqlite.exec('BEGIN');try{const results=[];for(const s of stmts)results.push(await s.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
globalThis.catalogEnv={DB:db,CATALOG_SECRET:'1'.repeat(64)};
for(const name of ['catalog-data','store-connectors','catalog-sync']){let code=await readFile('lib/'+name+'.ts','utf8');code=code.replace(/import \{\s*env\s*\} from ['"]cloudflare:workers['"];?/,'const env=globalThis.catalogEnv;');let js=ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;js=js.replace(/from '(\.\/[^']+)'/g,"from '$1.mjs'");await writeFile(path.join(out,name+'.mjs'),js);}
const data=await import(path.join(out,'catalog-data.mjs'));const stores=await import(path.join(out,'store-connectors.mjs'));const sync=await import(path.join(out,'catalog-sync.mjs'));
await data.ensureSamples();assert.equal((await db.prepare('SELECT count(*) AS n FROM products').first()).n,100);await data.ensureSamples();assert.equal((await db.prepare('SELECT count(*) AS n FROM products').first()).n,100);
let r=await sync.synchronize('demo-shopify');assert.equal(r.unchanged,50);assert.equal(r.added,0);assert.equal(r.updated,0);
const row=await db.prepare('SELECT payload FROM fixtures WHERE id=?').bind('demo-shopify:1').first();const fixture=JSON.parse(row.payload);fixture.price=9999;fixture.available=true;await db.prepare('UPDATE fixtures SET payload=? WHERE id=?').bind(JSON.stringify(fixture),'demo-shopify:1').run();r=await sync.synchronize('demo-shopify');assert.equal(r.updated,1);assert.equal((await db.prepare('SELECT price FROM products WHERE id=?').bind('demo-shopify:1').first()).price,9999);r=await sync.synchronize('demo-shopify');assert.equal(r.unchanged,50);
await db.prepare('UPDATE products SET suppressed=1 WHERE id=?').bind('demo-shopify:1').run();fixture.price=8000;await db.prepare('UPDATE fixtures SET payload=? WHERE id=?').bind(JSON.stringify(fixture),'demo-shopify:1').run();await sync.synchronize('demo-shopify');assert.equal((await db.prepare('SELECT suppressed FROM products WHERE id=?').bind('demo-shopify:1').first()).suppressed,1);
await assert.rejects(sync.synchronize('shopify'),/Connect this store/);assert.equal((await db.prepare('SELECT count(*) AS n FROM products').first()).n,100);assert.equal((await db.prepare("SELECT count(*) AS n FROM sync_runs WHERE status='failed'").first()).n,1);
const conn={type:'woocommerce',domain:'https://store.catalog-check.com',key:'ck_test',secret:'cs_test',currency:'USD'};await stores.saveConnection(conn);assert.deepEqual(await stores.readConnection('woocommerce'),conn);const encrypted=await db.prepare('SELECT value FROM settings WHERE id=?').bind('connection-woocommerce').first();assert.ok(!encrypted.value.includes('cs_test'));assert.throws(()=>stores.validateDomain({...conn,domain:'https://127.0.0.1'}));
let wooPages=[];globalThis.fetch=async(url)=>{const u=new URL(url);let page=Number(u.searchParams.get('page'));wooPages.push(page);const count=page===1?100:2;return Response.json(Array.from({length:count},(_,i)=>({id:(page-1)*100+i+1,name:'Woo '+i,sku:'W'+i,price:'14.50',description:'<p>Hello</p>',categories:[{id:1,name:'Rugs'}],images:[{src:'https://cdn.catalog-check.com/rug.webp'}],type:'simple',stock_status:'instock',status:'publish'})),{headers:{'x-wp-totalpages':'2'}})};
let imported=await stores.importWoo(conn);assert.equal(imported.length,102);assert.deepEqual(wooPages,[1,2]);assert.equal(imported[0].currency,'USD');assert.equal(imported[0].price,14.5);r=await sync.synchronize('woocommerce');assert.equal(r.added,102);r=await sync.synchronize('woocommerce');assert.equal(r.unchanged,102);
const before=JSON.stringify((await db.prepare("SELECT * FROM products WHERE source='woocommerce' ORDER BY id").all()).results);globalThis.fetch=async()=>new Response('{}',{status:401});await assert.rejects(sync.synchronize('woocommerce'),/rejected access/);const after=JSON.stringify((await db.prepare("SELECT * FROM products WHERE source='woocommerce' ORDER BY id").all()).results);assert.equal(before,after);
let requestCursors=[];globalThis.fetch=async(url,init)=>{const body=JSON.parse(init.body);requestCursors.push(body.variables.after);const page=body.variables.after?2:1;const nodes=Array.from({length:page===1?10:3},(_,i)=>({id:'gid://shopify/Product/'+((page-1)*10+i),title:'Shopify '+i,handle:'rug-'+i,productType:'Modern',description:'Description',status:'ACTIVE',images:{nodes:[{url:'https://cdn.shopify.com/rug.jpg'}],pageInfo:{hasNextPage:false}},variants:{nodes:[{id:'v'+i,title:'Small',sku:'S'+i,price:'100.00',inventoryQuantity:5,inventoryPolicy:'DENY',inventoryItem:{tracked:true},selectedOptions:[{name:'Size',value:'Small'}]}],pageInfo:{hasNextPage:false}}}));return Response.json({data:{shop:{currencyCode:'INR'},products:{nodes,pageInfo:{hasNextPage:page===1,endCursor:'cursor-1'}}}})};
imported=await stores.importShopify({type:'shopify',domain:'sample.myshopify.com',token:'secret'});assert.equal(imported.length,13);assert.deepEqual(requestCursors,[null,'cursor-1']);assert.equal(imported[0].variants[0].attributes.Size,'Small');assert.equal(imported[0].available,true);
const queryPlan=(await db.prepare('EXPLAIN QUERY PLAN SELECT * FROM products WHERE category_id=? AND suppressed=0').bind('abstract').all()).results;assert.ok(queryPlan.some(r=>r.detail.includes('products_category_visible')));
await db.prepare('INSERT INTO sync_locks(source,expires_at) VALUES(?,?)').bind('demo-shopify',Date.now()+10000).run();await assert.rejects(sync.synchronize('demo-shopify'),/already running/);
console.log('PASS: idempotent 100-product seed, change detection, repeat-sync deduplication, deletion suppression, error history, source outage preservation, encrypted credentials, domain validation, WooCommerce and Shopify pagination/normalization, category index, sync locking.');
