import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {isAdmin,validOrigin} from '@/lib/catalog-auth';
import {db,ensureSamples,categories,getConfig,unpack,upsertStatements,slug} from '@/lib/catalog-data';
import {readConnection,saveConnection,SourceError} from '@/lib/store-connectors';
import {synchronize} from '@/lib/catalog-sync';
export const dynamic='force-dynamic';
const image=z.string().max(2000).refine(s=>s.startsWith('/images/')||/^\/api\/images\/[a-z0-9/-]+\.webp$/.test(s)||(()=>{try{return new URL(s).protocol==='https:'}catch{return false}})(),'Use an HTTPS image URL or an uploaded image.');
const productSchema=z.object({id:z.string().max(200).optional(),name:z.string().trim().min(1).max(200),sku:z.string().max(100),price:z.coerce.number().min(0).max(1e10),currency:z.string().regex(/^[A-Z]{3}$/),description:z.string().max(20000),categoryId:z.string().min(1).max(100),available:z.boolean(),images:z.array(image).max(100),variants:z.array(z.object({id:z.string(),name:z.string().max(200),sku:z.string().max(100),price:z.coerce.number().min(0),available:z.boolean(),attributes:z.record(z.string()).optional()})).max(2000).default([]),url:z.string().max(2000).refine(s=>!s||(()=>{try{return new URL(s).protocol==='https:'}catch{return false}})())});
export async function GET(){if(!await isAdmin())return Response.json({error:'Admin access required.'},{status:403});try{await ensureSamples();const [rows,cats,config,runs,counts,fixtures]=await Promise.all([db().prepare('SELECT p.*,c.name AS category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.suppressed=0 ORDER BY p.updated_at DESC LIMIT 1100').all(),categories(true),getConfig(),db().prepare('SELECT * FROM sync_runs ORDER BY started_at DESC LIMIT 50').all(),db().prepare('SELECT source,COUNT(*) AS count FROM products WHERE suppressed=0 GROUP BY source').all(),db().prepare('SELECT id,source,payload FROM fixtures ORDER BY id').all<any>()]);
 const connections=await Promise.all(['shopify','woocommerce'].map(async type=>{const c=await readConnection(type);return {type,connected:!!c,domain:c?.domain||'',currency:c?.currency||config.currency};}));
 return Response.json({products:rows.results.map(unpack),categories:cats,config,runs:runs.results,counts:counts.results,connections,fixtures:fixtures.results.map((r:any)=>({id:r.id,source:r.source,product:JSON.parse(r.payload)}))},{headers:{'Cache-Control':'no-store'}});
 }catch(e){console.error('Admin load failed',e);return Response.json({error:'The workspace is temporarily unavailable. Please try again.'},{status:503});}}
export async function POST(request:Request){if(!await isAdmin())return Response.json({error:'Admin access required.'},{status:403});if(!validOrigin(request))return Response.json({error:'Request origin rejected.'},{status:403});try{await ensureSamples();const body:any=await request.json();let result:any={ok:true};
 if(body.action==='saveProduct'){const p=productSchema.parse(body.product);const cat=await db().prepare('SELECT name FROM categories WHERE id=?').bind(p.categoryId).first<any>();if(!cat)throw new SourceError('Choose an existing category.');let old:any=null;if(p.id){const r=await db().prepare('SELECT * FROM products WHERE id=? AND suppressed=0').bind(p.id).first();if(!r)throw new SourceError('This product no longer exists.');old=unpack(r);}
 const n={...p,externalId:old?.externalId||crypto.randomUUID(),source:old?.source||'manual',categoryName:cat.name,metadata:old?.metadata||{}};await db().batch(await upsertStatements([n]));result.id=n.source+':'+n.externalId;}
 else if(body.action==='deleteProduct'){const id=z.string().max(200).parse(body.id);await db().prepare('UPDATE products SET suppressed=1 WHERE id=?').bind(id).run();}
 else if(body.action==='saveCategory'){const c=z.object({id:z.string().max(100).optional(),name:z.string().trim().min(1).max(100),parentId:z.string().nullable(),visible:z.boolean(),sortOrder:z.coerce.number().int().min(0).max(9999)}).parse(body.category);const id=c.id||slug(c.name);if(c.parentId===id)throw new SourceError('A category cannot be its own parent.');if(c.parentId){const parent=await db().prepare('SELECT parent_id FROM categories WHERE id=?').bind(c.parentId).first<any>();if(!parent)throw new SourceError('Parent category not found.');if(parent.parent_id)throw new SourceError('Use a top-level parent category.');const children=await db().prepare('SELECT id FROM categories WHERE parent_id=? LIMIT 1').bind(id).first();if(children)throw new SourceError('A category with subcategories must stay at the top level.');}
 if(!c.id){const exists=await db().prepare('SELECT id FROM categories WHERE id=?').bind(id).first();if(exists)throw new SourceError('A category with this name already exists.');}
 await db().prepare('INSERT INTO categories(id,name,parent_id,visible,sort_order) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,parent_id=excluded.parent_id,visible=excluded.visible,sort_order=excluded.sort_order').bind(id,c.name,c.parentId,c.visible?1:0,c.sortOrder).run();}
 else if(body.action==='deleteCategory'){const id=z.string().max(100).parse(body.id);const n=await db().prepare('SELECT COUNT(*) AS n FROM products WHERE category_id=?').bind(id).first<any>();const children=await db().prepare('SELECT COUNT(*) AS n FROM categories WHERE parent_id=?').bind(id).first<any>();if(n.n||children.n)throw new SourceError('Move all products and subcategories before removing this category.');await db().prepare('DELETE FROM categories WHERE id=?').bind(id).run();}
 else if(body.action==='saveConfig'){const c=z.object({name:z.string().trim().min(1).max(100),whatsapp:z.string().refine(x=>!x||/^[1-9][0-9]{7,14}$/.test(x),'Enter digits with country code, without + or spaces.'),design:z.enum(['gallery','studio']),currency:z.string().regex(/^[A-Z]{3}$/)}).parse(body.config);await db().prepare('INSERT INTO settings(id,value) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind('catalog',JSON.stringify(c)).run();}
 else if(body.action==='saveConnection'){const c=z.object({type:z.enum(['shopify','woocommerce']),domain:z.string().trim().max(500),token:z.string().max(2000).optional(),key:z.string().max(500).optional(),secret:z.string().max(500).optional(),currency:z.string().regex(/^[A-Z]{3}$/).optional()}).parse(body.connection);const old=await readConnection(c.type);const changed=!!old&&old.domain!==c.domain;if(changed){const n=await db().prepare('SELECT COUNT(*) AS n FROM products WHERE source=?').bind(c.type).first<any>();if(n.n)throw new SourceError('This store already has imported products. A store migration requires a separate source identifier.');}await saveConnection({...c,token:c.token||old?.token,key:c.key||old?.key,secret:c.secret||old?.secret});}
 else if(body.action==='disconnect'){const type=z.enum(['shopify','woocommerce']).parse(body.source);await db().prepare('DELETE FROM settings WHERE id=?').bind('connection-'+type).run();}
 else if(body.action==='sync')result=await synchronize(z.string().parse(body.source));
 else if(body.action==='editFixture'){const id=z.string().max(200).parse(body.id);const price=z.coerce.number().min(0).max(1e10).parse(body.price);const available=z.boolean().parse(body.available);const row=await db().prepare('SELECT payload FROM fixtures WHERE id=?').bind(id).first<any>();if(!row)throw new SourceError('Sample source product not found.');const p=JSON.parse(row.payload);p.price=price;p.available=available;for(const v of p.variants){v.price=price;v.available=available;}await db().prepare('UPDATE fixtures SET payload=? WHERE id=?').bind(JSON.stringify(p),id).run();}
 else throw new SourceError('Unknown workspace action.');return Response.json(result);
 }catch(e){if(e instanceof z.ZodError)return Response.json({error:e.issues[0]?.message||'Check the entered values.'},{status:400});if(e instanceof SourceError)return Response.json({error:e.message},{status:400});console.error('Admin action failed');return Response.json({error:'The change could not be saved. Please try again.'},{status:500});}}
